// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWB5NHKPG4lAF5GgPs3M2JeNJ-U0G2aV8',
    appId: '1:550016293282:web:95bf5de2e6c7ec9fc63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    authDomain: 'salimstore-f1830.firebaseapp.com',
    databaseURL: 'https://salimstore-f1830-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    measurementId: 'G-S56376RNE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UrT3a4Vc9UO-zVaS3GS3-uvrjVuWTRs',
    appId: '1:550016293282:android:3af432aef102dc3bc63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL: 'https://salimstore-f1830-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCW4aUzrF3ALilXOqNIaDl8bjOqmx3Ig',
    appId: '1:550016293282:ios:261b1474c595079ac63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL: 'https://salimstore-f1830-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    iosBundleId: 'com.livriyes.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgCW4aUzrF3ALilXOqNIaDl8bjOqmx3Ig',
    appId: '1:550016293282:ios:6f8926f9d4ba622fc63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL: 'https://salimstore-f1830-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    iosBundleId: 'com.livriyes.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWB5NHKPG4lAF5GgPs3M2JeNJ-U0G2aV8',
    appId: '1:550016293282:web:e1ce124fdf687a33c63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    authDomain: 'salimstore-f1830.firebaseapp.com',
    databaseURL: 'https://salimstore-f1830-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    measurementId: 'G-D9ENYVLQCW',
  );

}
