// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWB5NHKPG4lAF5GgPs3M2JeNJ-U0G2aV8',
    appId: '1:550016293282:web:41c120c1d854e6c3c63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    authDomain: 'salimstore-f1830.firebaseapp.com',
    databaseURL: 'https://salimstore-f1830.firebaseio.com',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    measurementId: 'G-L4XQ7VQBVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UrT3a4Vc9UO-zVaS3GS3-uvrjVuWTRs',
    appId: '1:550016293282:android:f96322979fa3280ac63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL: 'https://salimstore-f1830.firebaseio.com',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCW4aUzrF3ALilXOqNIaDl8bjOqmx3Ig',
    appId: '1:550016293282:ios:1d70ac71ec38f4f7c63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL: 'https://salimstore-f1830.firebaseio.com',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    iosBundleId: 'com.livriyes.Livriyes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgCW4aUzrF3ALilXOqNIaDl8bjOqmx3Ig',
    appId: '1:550016293282:ios:bdc65eb2302c5f1cc63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    databaseURL:
        'https://salimstore-f1830.firebaseio.com',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    iosBundleId: 'com.livriyes.Livriyes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWB5NHKPG4lAF5GgPs3M2JeNJ-U0G2aV8',
    appId: '1:550016293282:web:7b58d9c579222a29c63afb',
    messagingSenderId: '550016293282',
    projectId: 'salimstore-f1830',
    authDomain: 'salimstore-f1830.firebaseapp.com',
    databaseURL: 'https://salimstore-f1830.firebaseio.com',
    storageBucket: 'salimstore-f1830.firebasestorage.app',
    measurementId: 'G-3PF7XLWNJM',
  );

}